### ISSUE TITLE
Which fonts from nerd-fonts are required?

### ISSUE THREAD

**Issue by michaldev** [wfxr/tmux-power#15]
Which fonts from nerd fonts are required for default tmux-power icons?

**Comment by wfxr** [comment]
I think any one of them should be fine?

**Comment by Reedyseth** [comment]
On macOS
I did install the JetBrains fonts as suggested from nerd fonts on this link:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono/Ligatures#brew-macos-only
I am not able to see the rendered icons. I only get to see this:
![Screen Shot 2022-05-12 at 20 25 07](https://user-images.githubusercontent.com/1228711/168199058-6926ef12-5442-4508-87bd-0de6d2d5dade.png)

**Comment by uniform641** [comment]
`Fira Code` shows missing icons
`MesloLGS NF` seems a perfect match
