### ISSUE TITLE
Theme not being applied

### ISSUE THREAD

**Issue by JwanKhalaf** [wfxr/tmux-power#16]
Apologies in advance, this is probably my fault, but there was nothing in the read me about this.

Here's my config:

```
set -g @tmux_power_theme 'moon'

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

If I'm not mistaken, I should see the nice moon theme that `tmux-power` provides, but I'm not seeing anything. I still get the standard bar at the bottom.

What am I doing wrong?

**Comment by berlotto** [comment]
For me too. One different theme of the default is not applied.

**Comment by wfxr** [comment]
Sorry I can't repro. Have you installed the plugin after adding it in your `tmux.conf`?

> 1. Add new plugin to `~/.tmux.conf` with `set -g @plugin '...'`
> 2. Press `prefix` + <kbd>I</kbd> (capital i, as in **I**nstall) to fetch the plugin.

**Comment by JwanKhalaf** [comment]
I'm an idiot, I am new to TPM, I missed the bit where I had to press `prefix` + <kbd>I</kbd>
