### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by poteto** [wfxr/tmux-power#2]
Hi, thanks for the theme, it's great! Would it be possible to have a version without the included icons? Not all fonts include these glyphs. I'm using Meslo from powerline-fonts.

<img width="1017" alt="Screen Shot 2020-07-06 at 12 04 56 PM" src="https://user-images.githubusercontent.com/1390709/86630031-26270800-bf81-11ea-950b-695271af161d.png">

**Comment by wfxr** [comment]
Hi @poteto thanks for your feedback. The font used in screenshot is from this repo https://github.com/ryanoasis/nerd-fonts. I added support for customizing the icons. You can set or disable each of them now.

**Comment by poteto** [comment]
Thanks, it works great!

**Comment by slier81** [comment]
Sorry to ask, how did you change font to use font from the NerdFont?

**Comment by wfxr** [comment]
Font is controlled by terminal emulator, not tmux. @slier81

**Comment by slier81** [comment]
can you tell me how to do it or link me to some article?
i having a hard time to do it, `dpkg reconfigure console-setup` doesnt help much

**Comment by whogurdevil** [comment]
> 

can you please tell me how did you manage to do this?

**Comment by rlvilla** [comment]
@whogurdevil install a nerdfont enabled font from the following repo, select it as your default in your terminal and reboot your machine if it doesn't refresh
https://github.com/ryanoasis/nerd-fonts
