### ISSUE TITLE
can not get icon printed for some of them

### ISSUE THREAD

**Issue by jerome-diver** [wfxr/tmux-power#20]
Hello and thank you for this plugin theme setting.
I can not get icon for User and some other (but calendar icon is printing for date).
I'm under FreeBSD-12.2 server on a VPS, i access from SSH through ssh command (and i can get icons on my oh-my-zsh prompt shell configured... even inside tmux).
Font used for oh-my-zsh theme (powerlevel10k) is nerdfont.

**Comment by wfxr** [comment]
I'm afraid can't provide much help. You can check your terminal & font settings.
