### ISSUE TITLE
Non-active window names are not being displayed

### ISSUE THREAD

**Issue by Gnyblast** [wfxr/tmux-power#26]
Hi I installed tmux-power with tmp and did the configurations, all looking good but I'm unable to see the window names that is not active but I only can see active window name even if there are many other windows.
![tmux-power](https://user-images.githubusercontent.com/28509323/163938154-5aec72c2-6593-4b78-b03f-90df06c0a223.png)
.

This is how my configurations looks like;
```
set -g @tmux_power_theme 'moon'
set -g @tmux_power_date_icon ' ' # set it to a blank will disable the icon
set -g @tmux_power_time_icon '🕘' # emoji can be used if your terminal supports
set -g @tmux_power_user_icon 'U'
set -g @tmux_power_session_icon 'S'
set -g @tmux_power_upload_speed_icon '↑'
set -g @tmux_power_download_speed_icon '↓'
set -g @tmux_power_prefix_highlight_pos 'LR'
set -g @tmux_power_show_upload_speed true
set -g @tmux_power_show_download_speed true
set -g @tmux_power_show_web_reachable true

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'wfxr/wmux-web-reachable'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
when I add the `set -g status-fg white` command to the end of `~/.tmux.conf`they gets visible but without the arrow like background coloring that you guys have on the screenshots.

**Comment by wfxr** [comment]
Sorry I can't repro. I guess it might have something to do with the color scheme of your terminal?

**Comment by Gnyblast** [comment]
I'm not sure, I tried bunch of other color schemes and tried on different terminal apps like; terminator or ubuntu default etc. Still same. Ok not a big deal just wondered if I'm missing any config in my tmux.conf

**Comment by Gnyblast** [comment]
Recent had a new PC and setup this again there. I had not exactly same problem but was looking similar.
`sudo apt-get install -y fonts-powerline` solved the issue.
