### ISSUE TITLE
IP instead of hostname

### ISSUE THREAD

**Issue by pablopunk** [wfxr/tmux-power#27]
Hi! Awesome plugin, thank you!

I have one question: My machine is showing the IP instead of the actual hostname, how can I change that to the hostname? 🙏🏻 

![CleanShot 2022-07-21 at 15 13 46](https://user-images.githubusercontent.com/4324982/180222486-ca2b5d93-66b0-46fc-900e-f5c5b3839981.png)

**Comment by wfxr** [comment]
@pablopunk weird, this was interpretered from `#h` which should not be possible to be the ip address. Maybe your hostname is actually `ip-192-168-1-143`? Check it by running `hostname` in your shell.

**Comment by pablopunk** [comment]
@wfxr ok I see the issue. Mac's sharing options show the name "m1pro" but the command hostname shows:

![CleanShot 2022-07-22 at 11 44 58](https://user-images.githubusercontent.com/4324982/180413892-1bcb3bee-b6aa-4ce9-9ac0-5a2c82df4965.png)

Changing again the name (via sharing options) will make hostname show the proper name but immediately switch back to the IP thing. Removing the `aws-cli` from my mac solved the issue 🙃.
