### ISSUE TITLE
request: alternating background color for windows

### ISSUE THREAD

**Issue by pcroland** [wfxr/tmux-power#3]
Hi!

I really like your theme, exactly what I was looking for except one thing:
It would be nice if the pane names had alternating background colors.
Something like this:
![image1](https://widevine.is-a.fail/DO11A0.png) (just a quick PS)
I would really appreciate this feature.

**Comment by wfxr** [comment]
Weird...Inactive window name should have the same background and foreground:
![image](https://user-images.githubusercontent.com/6105425/93155528-e1fe7380-f738-11ea-9b6a-2c4165a4ee50.png)
Why the last two window names in your screenshots looks different?

**Comment by pcroland** [comment]
It's a request, not a bug report. The image I showed is just a photoshopped image. It would be nice to have an option to alternate the background colors for the window names.

**Comment by wfxr** [comment]
Understood. Thanks for your suggestion @pcroland . I will consider it when I finish the things at hand.

**Comment by wfxr** [comment]
Hi @pcroland Sorry for the late reply. I find it difficult to add an option to meet similar needs, such as foreground, background, font style, etc. Instead it's simple for user to custom every part of tmux. You can easily change the `window-status-format`: 

```tmux
set -gq window-status-format "#[fg=#262626,bg=#4e4e4e]#[fg=#080808,italics] #I:#W#F #[fg=#4e4e4e,bg=#262626]"
```
Put it under `run '~/.tmux/plugins/tpm/tpm'` if you use `tmp`. This will give you a window status like this:
![image](https://user-images.githubusercontent.com/6105425/93732264-25f2ec00-fc03-11ea-820c-e77a0b100424.png)
