### ISSUE TITLE
Hide user

### ISSUE THREAD

**Issue by lcfd** [wfxr/tmux-power#34]
Hello! Is it possible to hide the user?
It's not really helpful to me and it occupies a lot of space.

**Comment by OkkarMin** [comment]
Hey @lcfd

I wanted to find out how to do it too and did the followings

```bash
# ~/.config/tmux/plugins/tmux-power/tmux-power.tmux
...
# line 122
user=okar
LS="#[fg=$G04,bg=$TC,bold] $user_icon $user #[fg=$TC,bg=$G06,nobold]$right_arrow_icon#[fg=$TC,bg=$G06] $session_icon #S "
...
```

<img width="888" alt="image" src="https://github.com/wfxr/tmux-power/assets/24297303/70f75238-65d6-4e05-aee6-11359056a53f">
