### ISSUE TITLE
custom theme is not shown when entering tmux

### ISSUE THREAD

**Issue by winsphinx** [wfxr/tmux-power#42]
This is my `.tmux.conf` file: 
```
# keys
bind r source-file ~/.tmux.conf

# options
set -g prefix C-b
set -g prefix2 C-x

set -g mouse on

set -g mode-keys vi

# plugins
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'forest'
```
but every time when entering tmux, the theme is default, I have to refresh it by `<prefix>+I`, it can switch to the 'forest theme'. But when I logout tmux and login next time, it is set to default again.

**Comment by wfxr** [comment]
Hi @winsphinx You should always set plugin options before tpm loading (i.e. the line `run '~/.tmux/plugins/tpm/tpm'`).

**Comment by winsphinx** [comment]
Thanks a lot.
