### ISSUE TITLE
all users to set own FG/BG values

### ISSUE THREAD

**Issue by maximus12793** [wfxr/tmux-power#7]
currently hardcoded and produces some weird coloring if the terminal theme does not match the hex codes provided. Would be nice to see this as a param like the Theme color.

**Comment by wfxr** [comment]
@maximus12793 As described in READEME:

> You can define your favourite main color if you don't like any of above.
> `set -g @tmux_power_theme '#483D8B' # dark slate blue`

**Comment by maximus12793** [comment]
Sure. This is to change the (border*** colors) not the general theme. This
would be the active foreground and background, not the general color scheme

**Comment by wfxr** [comment]
Sorry, background is one of the things I don't want to make it customizable. Please use `tmux set` directly to override the defaults If one needs extremely high customization. Or you can freely fork this repo and do the chagnes as you wish.

**Comment by maximus12793** [comment]
@wfxr using `tmux set` does not work in this case due to the way tpm loads plugins, it will briefly change, then be overridden by your plugin.

**Comment by wfxr** [comment]
@maximus12793 You should leave them after `run '~/.tmux/plugins/tpm/tpm'`.
